config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
      root to: 'pages#home', as: :authenticated_root
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :employees
  resources :companies do
    resources :genbas, only: [:new, :create]
  end
  resources :genbas, only: [:destroy]
  resources :puntos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :genbas, dependent: :destroy
  has_many :puntos, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many_attached :photos
  ROLES = %w(Denkiya Shokucho)

  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true, numericality: { only_integer: true }
  validates :email, presence: true
  validates :role, inclusion: { in: ROLES }
  validates :level_employee, inclusion: { in: 0..5 }
  validates :level_employee, numericality: { only_integer: true }
  validates :started_date, presence: true

  has_many :puntos, dependent: :destroy
end

app/models/genba.rb
class Genba < ApplicationRecord
  belongs_to :company

  has_many :puntos, dependent: :destroy
end

app/models/punto.rb
class Punto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :puntos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path
  end

  private

  def find_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(
      :name, :furigana, :ceo, :address, :address2,
      :phone, :fax, :contact, :email, :closure
    )
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(
      :name, :furigana, :address, :phone,
      :email, :role, :job_exp, :started_date, :drive_licence,
      :pay_number, :licence1, :licence2, :licence3,
      :licence4, :licence5, :level_employee, :healthy_exam,
      :document, :document_date, :passport, :passport_date,
      photos: []
    )
  end
end

app/controllers/genbas_controller.rb
class GenbasController < ApplicationController
  before_action :find_company, except: [:destroy]

  def new
    @genba = Genba.new
  end

  def create
    @genba = Genba.new(genba_params)
    @genba.company = @company
    if @genba.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def destroy
    @genba = Genba.find(params[:id])
    @company = @genba.company_id
    @genba.destroy
    redirect_to company_path(@genba.company)
  end

  private

  def find_company
    @company = Company.find(params[:company_id])
  end

  def genba_params
    params.require(:genba).permit(:name, :address, :contact, :phone, :closure)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/puntos_controller.rb
class PuntosController < ApplicationController
  before_action :find_user

  def index
    @puntos = Punto.all
  end

  def show
    @punto = current_user.puntos.all
  end

  def new
    if !current_user.puntos.last
      @punto = Punto.new
    else
    @punto = current_user.puntos.last
      if @punto.out
        @punto = Punto.new
      end
    end
  end

  def create
    @punto = Punto.new(punto_params)
    @punto.user = @user
    if @punto.save
      redirect_to new_punto_path(@punto)
    else
      flash.alert = "No punto"
      render :new
    end
  end

  def edit
  end

  def update
    @punto = current_user.puntos.last
    if @punto.in
      @punto.update(punto_params)
      redirect_to authenticated_root_path
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(current_user.id)
  end

  def punto_params
    params.require(:punto).permit(
    :in, :out, :date, :note,
    :active, :weekend, :night_shift,
    :day, :night, :day_off
  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(company) do |f| %>
<%= f.input :name %>
<%= f.input :furigana %>
<%= f.input :ceo %>
<%= f.input :address %>
<%= f.input :address2 %>
<%= f.input :phone %>
<%= f.input :fax%>
<%= f.input :contact %>
<%= f.input :email %>
<%= f.input :closure%>
<%= f.submit company.persisted? ? 'Editar' : 'Criar', class: 'btn btn-outline-primary w-100' %>
<% end %>

app/views/companies/edit.html.erb
<h1 class="mb-5 text-center">Editar Empresa</h1>

<%= render 'companies/form', company: @company %>

app/views/companies/index.html.erb
<div class="container d-flex flex-column mt-5 align-items-center">
  <div class="row justify-content-center">
    <%= image_tag "logo.png", alt: "alttext", class: 'p-5 mt-5' %>
  </div>

  <h1 class="mb-5 text-center">Empresas</h1>
  <%= link_to 'Voltar', authenticated_root_path, class: 'btn btn-info mb-3' %>
  <%= link_to 'Criar Nova Empresa', new_company_path, class: 'btn btn-primary w-50 mb-4' %>
  <ul class="list-group mb-3">
    <% @companies.each do |company| %>
    <li class="list-group-item">
      <div class="row justify-content-between align-items-center">
        <div>
          <strong><%= company.name %></strong>
        </div>
        <div>
          <%= link_to 'Visualizar', company_path(company), class: 'btn btn-primary' %>
          <%= link_to 'Editar', edit_company_path(company), class: 'btn btn-secondary' %>
          <%= link_to 'Deletar', company_path(company),
          method: :delete,
          data: { confirm: 'Tem certeza?' },
          class: 'btn btn-danger' %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/companies/new.html.erb
<div class="container">
<h1 class="mb-5 text-center">Registro de Nova Empresa</h1>

<%= render 'companies/form', company: @company %>

<%= link_to 'Inicio', companies_path, class: 'btn btn-outline-success w-100' %>
</div>

app/views/companies/show.html.erb
<div class="container p-5">
  <div class="row">
    <div class="container mt-5">
      <h1 class="mb-5 text-center"><%= @company.name %>
        <p><%= @company.furigana %></p>
      </h1>

      <p>Dono: <%= @company.ceo %></p>
      <p>Endereço: <%= @company.address %></p>
      <p>Endereço: <%= @company.address2 %></p>
      <p>Contato: <%= @company.contact %></p>
      <p>Telefone: <%= @company.phone %></p>
      <p>Fax: <%= @company.fax %></p>
      <p>Email: <%= @company.email %></p>
      <p>Fechamento: <%= @company.closure %></p>

      <%= link_to 'Voltar', companies_path, class: ' btn btn-info mb-5' %>
    </div>

    <div class="container">

      <h1 class="mb-5 text-center">Genbas</h1>
      <%= link_to 'Criar novo genba', new_company_genba_path(@company), class: 'btn btn-primary mb-5'  %>

      <div class="row justify-content-around">
        <% @company.genbas.each do |genba| %>
        <div class="card text-center mb-5">
          <div class="card-header">
           Name: <%= genba.name %>
         </div>
         <div class="card-body">
          <p class="card-title"> <span>Contact: </span> <%= genba.contact %></p>
          <p class="card-text">
            Address: <%= genba.address %>
          </p>
          <p>Closure: <%= genba.closure %></p>
        </div>
        <div class="card-footer text-muted">
          Phone: <%= genba.phone %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>
</div>

app/views/employees/_form.html.erb
<%= simple_form_for(employee) do |f| %>
<%= f.input :photos, as: :file, input_html: { multiple: true } %>
<%= f.input :name, label: '氏名 (Nome Completo):' %>
<%= f.input :furigana %>
<%= f.input :address %>
<%= f.input :phone %>
<%= f.input :email %>
<%= f.input :role, collection: Employee::ROLES %>
<%= f.input :level_employee, collection: 1..5 %>
<%= f.input :started_date %>
<%= f.input :job_exp %>
<%= f.input :pay_number %>
<div class="row justify-content-around">
<%= f.input :licence1, as: :boolean %>
<%= f.input :licence2, as: :boolean %>
</div>
<div class="row justify-content-around">
<%= f.input :licence3, as: :boolean %>
<%= f.input :licence4, as: :boolean %>
</div>
<%= f.input :licence5, as: :boolean, label: 'Driver Licence:' %>
<%= f.input :drive_licence %>
<%= f.input :healthy_exam %>
<%= f.input :document, label: 'Zairyo Card'  %>
<%= f.input :document_date, label: 'Vencimento' %>
<%= f.input :passport %>
<%= f.input :passport_date, label: 'Vencimento' %>
<br>
<div class="d-flex justify-content-center">
<%= f.submit employee.persisted? ? 'Editar' : 'Criar', class: 'btn btn-primary w-50' %>
</div>
<% end %>

app/views/employees/edit.html.erb
<div class="container mt-5 mb-5 p-5">
  <h1 class="mb-5 text-center">Editar Funcionário</h1>
  <div class="row justify-content-center">
    <%= link_to 'Voltar', employees_path, class: 'btn btn-info mt-2 mb-5' %>
  </div>
  <%= render 'employees/form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="container d-flex flex-column mt-5 align-items-center">
  <div class="row justify-content-center">
    <%= image_tag "logo.png", alt: "alttext", class: 'p-5 mt-5' %>
  </div>

  <h1 class="mb-3 text-center">Funcionários</h1>
  <%= link_to 'Voltar', authenticated_root_path, class: 'btn btn-info mb-3' %>
  <%= link_to 'Criar Novo Funcionário', new_employee_path, class: 'btn btn-primary w-50 mb-4' %>
  <ul class="list-group mb-3">
    <% @employees.order(:name).each do |employee| %>
    <li class="list-group-item">
      <div class="row justify-content-between align-items-center">
        <div>
          <strong><%= employee.name %></strong>
        </div>
        <div>
          <%= link_to 'Visualizar', employee_path(employee), class: 'btn btn-primary' %>
          <%= link_to 'Editar', edit_employee_path(employee), class: 'btn btn-secondary' %>
          <%= link_to 'Deletar', employee_path(employee), class: 'btn btn-danger', method: :delete, data: { confirm: 'Tem certeza?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/employees/new.html.erb
<div class="container">
<h1 class="text-center">Registro de Novo Funcionário</h1>

<%= render 'employees/form', employee: @employee %>

<%= link_to 'Voltar', employees_path, class: 'btn btn-info mt-2 mb-5' %>
</div>

app/views/employees/show.html.erb
<div class="container p-5">
  <div class="mt-5 mb-5">
    <h1 class="text-center"><%= @employee.name %> ( <small><%= @employee.role %></small> ) </h1>
  </div>
  <div class="show-employee">
    <% @employee.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
    <% end %>
    <span>Número:</span>
    <p><%= @employee.pay_number %></p>
    <span>Nome Completo:</span>
    <p><%= @employee.name %></p>
    <span>Furigana:</span>
    <p><%= @employee.furigana %></p>
    <span>Endereço:</span>
    <p>Endereço: <%= @employee.address %></p>
    <div class="row justify-content-around" style="margin: 0;">
      <div>
        <span>Telefone:</span>
        <p><%= @employee.phone %></p>
        <div>
          <span>Email:</span>
        <p><%= @employee.email %></p>
        </div>
      </div>
    </div>
    <div class="row justify-content-around" style="margin: 0;">
      <p>Cargo: <%= @employee.role %></p>
      <p>Level: <%= @employee.level_employee %></p>
    </div>
    <div class="row justify-content-around" style="margin: 0;">
      <p>Data Inicio: <%= @employee.started_date %></p>
      <p>Tempo de experiência: <%= @employee.job_exp %></p>
    </div>
  </div>
  <div class="row justify-content-around">
    <p>Licença 1: <%= @employee.licence1 ? 'Ok' : 'No' %></p>
    <p>Licença 2: <%= @employee.licence2 ? 'Ok' : 'No' %></p>
    <p>Licença 3: <%= @employee.licence3 ? 'Ok' : 'No' %></p>
    <p>Licença 4: <%= @employee.licence4 ? 'Ok' : 'No' %></p>
  </div>
  <div class="driver-licence">
    <p>Driver Licence: <%= @employee.licence5 ? 'Ok' : 'No' %> Venc. <%= @employee.drive_licence %></p>
  </div>
  <div class="row justify-content-around">
    <p>Passaporte: <%= @employee.passport %> - Venc. <%= @employee.passport_date %></p>
    <p>Zairyo Card: <%= @employee.document %> Venc. <%= @employee.document_date %></p>
  </div>
  <%= link_to 'Voltar', employees_path, class: ' btn btn-primary' %>
</div>

app/views/genbas/_form.html.erb
<%= simple_form_for [company, genba] do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone %>
<%= f.input :contact %>
<%= f.input :closure %>
<%= f.submit class: 'bnt btn-outline-info' %>
<% end %>

app/views/genbas/new.html.erb
<h1 class="mb-5 text-center">Registro de Novo Genba</h1>

<%= render 'genbas/form', genba: @genba, company: @company %>

<%= link_to 'Voltar', company_path(@company), class: 'btn btn-info w-100' %>

app/views/genbas/show.html.erb
<p>Genba</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YudenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

      <%= yield %>

    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container d-flex flex-column mt-5 align-items-center">
  <div class="row justify-content-center">
    <%= image_tag "logo.png", alt: "alttext", class: 'p-5 mt-5' %>
  </div>
  <% if current_user.admin == true  %>
  <%= link_to 'Funcionários', employees_path, class: 'btn btn-primary w-50 mb-3' %>
  <%= link_to 'Empresas', companies_path, class: 'btn btn-success w-50 mb-3' %>
  <%= link_to 'Ponto', new_punto_path, class: 'btn btn-info w-50 mb-3' %>
  <% else %>
  <%= link_to 'Ponto', new_punto_path, class: 'btn btn-info w-50 mb-3' %>
  <% end %>
</div>

app/views/puntos/_form.html.erb
<%= simple_form_for [punto] do |f| %>
<%= f.input :day %>
<%= f.input :night %>
<%= f.input :day_off %>
<%= f.input :date %>
<% if punto.in %>
<%= f.input :out, as: :time, html5: true, input_html: { value: Time.now.strftime("%k:%M") } %>
<% else %>
<%= f.input :in, as: :time, html5: true, input_html: { value: Time.now.strftime("%k:%M") } %>
<% end %>
<% if punto.out %>
<%= f.input :note %>
<% else %>
<%= f.input :note, as: :hidden %>
<% end %>
<%= f.input :weekend %>
<%= f.input :night_shift %>
<% if punto.in %>
<%= f.submit "Check Out" %>
<% else %>
<%= f.submit "Check In" %>
<% end %>

<% end %>

app/views/puntos/index.html.erb
index.html.erb

app/views/puntos/new.html.erb
<div class="container d-flex flex-column mt-5 align-items-center">
<h1 class="mb-5 text-center mt-5">Punto</h1>

<%= render 'puntos/form', punto: @punto, user: @user %>

</div>

app/views/puntos/show.html.erb
<div class="container d-flex flex-column mt-5 align-items-center">
<h1>Report</h1>




<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">In</th>
      <th scope="col">Out</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
<% current_user.puntos.each do |punto| %>

  <tbody>
    <tr>
      <th scope="row"><%= current_user.id %></th>
      <td><%= punto.date %></td>
      <td><%= punto.in.strftime("%k:%M") %></td>
      <td><%= punto.out %></td>
      <td><%= punto.user.email %></td>
    </tr>
  </tbody>
<% end %>
</table>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to image_tag("icon.png"), new_user_session_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <p id="current-user-email"><%= current_user.email %></p>
      </li>
      <% if current_user.admin == true  %>
      <li class="nav-item dropdown">
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Relatório", punto_path(current_user), class: "dropdown-item" %>
          <%= link_to "Admin", rails_admin_path, class: "dropdown-item" %>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Relatório", punto_path(current_user), class: "dropdown-item" %>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
        <% end %>
        <% end %>
    </ul>
  </div>
</div>